import mlx.core as mx
from mlx_lm import load
from tsp_mlx.sparse_cache import KVCacheManager
from tsp_mlx.cortex_hook import CortexHook
from tsp_mlx.inference import patch_attention_for_extraction
from mlx_lm.models.cache import make_prompt_cache
import logging

logging.basicConfig(level=logging.INFO, format="%(message)s")

print("\033[1;36m=== Initializing TSP Engine (Qwen2.5-Coder-7B-Instruct-4bit) ===\033[0m")
model, tokenizer = load("mlx-community/Qwen2.5-Coder-7B-Instruct-8bit")
patch_attention_for_extraction(model)

class DemoHook:
    def __init__(self):
        self.edges = set()
        self.last_lambda_2 = 0.5
        
    def evaluate_attention(self, attn, sinks, pos):
        # Force an island eviction on tokens 10 through 40
        if len(pos) > 20:
            return {"action": "GARBAGE_COLLECT", "island_indices": pos[10:40]}
        return {"action": "ALLOW", "island_indices": []}

hook = DemoHook()
manager = KVCacheManager(hook, model=model, enable_compression=True, enable_consolidation=True, head_dim=128)
manager.consolidator.salience_threshold = 0.0 # Force TTT to run
model._tsp_kv_manager = manager

# Setup dummy context
prompt = mx.array([[0] * 100])
cache = make_prompt_cache(model)
manager.position_tracker.step(prompt.shape[1])
logits = model(prompt, cache=cache)

attn = mx.zeros((1, 1, 1, 100))
attn[0, 0, 0, 0:5] = 1.0 # Attend to sinks
manager.last_attention_matrix = attn
raw_caches = [(c.keys, c.values) for c in cache]
dummy_x = mx.random.normal((1, 100, 3584))

print("\n\033[1;35m=== SCENARIO 1: Trusted Memory Consolidation ===\033[0m")
print("Evicting 'Thought Island' (Tokens 10-40) generated by the Agent...")
manager.update(attn, raw_caches, sinks=[0,1,2,3,4], x=dummy_x)

print("\n\033[1;35m=== SCENARIO 2: Untrusted 'Read-Only' Data ===\033[0m")
print("Agent ingested an untrusted file from a user. Evicting the same Island...")
manager.untrusted_indices = set(range(10, 40)) # Mark island as untrusted
attn2 = mx.zeros((1, 1, 1, len(manager.position_tracker.position_ids)))
manager.update(attn2, raw_caches, sinks=[0,1,2,3,4], x=dummy_x)

print("\n\033[1;35m=== SCENARIO 3: Topological Compression & Cryptographic Salting ===\033[0m")
if manager.topological_pages:
    macro_id = list(manager.topological_pages.keys())[0]
    print(f"Stored Topological Page for Macro-Token Position ID: {macro_id}")
    print(f"Session Salt used for Macro-Token Encryption: {manager.compressor_k.session_salt.shape} (Randomized per boot)")

print("\n\033[1;35m=== SCENARIO 4: Semantic Firewall (Dual Spike Intercept) ===\033[0m")
real_hook = CortexHook()
real_hook.threat_indices = {10}    # E.g., The token for 'rm' or 'z3'
real_hook.execution_indices = {20} # E.g., The token for '<execute>'

attn_firewall = mx.zeros((1, 1, 1, 30))
attn_firewall[0, 0, 0, 10] = 0.9 # High attention on Threat
attn_firewall[0, 0, 0, 20] = 0.9 # High attention on Execution
print("LLM Attention Matrix spikes simultaneously on a Threat and Execution target...")
decision = real_hook.evaluate_attention(attn_firewall, sinks=[], position_ids=list(range(30)))
print(f"\nFinal Firewall Decision: {decision['action']}")
